import js from '@eslint/js'
import jsxA11y from 'eslint-plugin-jsx-a11y'
import globals from 'globals'
import reactHooks from 'eslint-plugin-react-hooks'
import reactRefresh from 'eslint-plugin-react-refresh'
import tseslint from 'typescript-eslint'

export default tseslint.config(
  { ignores: ['dist'] },
  {
    // Fase 26 (Hardening, plan Bloque 5): jsx-a11y added for the first time
    // across the whole SPA, `recommended` preset (34 rules at `error`
    // severity) - verified active against a synthetic violation, and zero
    // real findings across the existing component tree (shadcn/Radix
    // already apply good accessibility practices by construction).
    extends: [
      js.configs.recommended,
      ...tseslint.configs.recommended,
      jsxA11y.flatConfigs.recommended,
    ],
    files: ['**/*.{ts,tsx}'],
    languageOptions: {
      ecmaVersion: 2020,
      globals: globals.browser,
    },
    plugins: {
      'react-hooks': reactHooks,
      'react-refresh': reactRefresh,
    },
    rules: {
      ...reactHooks.configs.recommended.rules,
      'react-refresh/only-export-components': ['warn', { allowConstantExport: true }],
    },
  },
  {
    // src/api/client.ts is generated by orval from openapi.json (ADR 0007) -
    // never hand-edited, regenerated wholesale by `make contracts`. Bumping
    // eslint-plugin-react-hooks 5->7 added `react-hooks/refs` and
    // `react-hooks/immutability`, both of which misfire on orval's own
    // boilerplate (`query.queryKey = queryOptions.queryKey`, emitted after
    // every `useQuery` call) as if it were an unsafe mutation of a hook's
    // return value during render - it's a plain property assignment on a
    // fresh local object, not a ref, and orval controls this pattern, not
    // us. Scoped to these two rules/this one file rather than ignoring the
    // file outright, so any other rule (unused vars, etc.) still catches a
    // real regeneration mistake.
    files: ['src/api/client.ts'],
    rules: {
      'react-hooks/refs': 'off',
      'react-hooks/immutability': 'off',
    },
  },
)
