/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * ProcuraWise API
 * OpenAPI spec version: 0.1.0
 */
export type HealthHealthGet200 = {[key: string]: string};

/**
 * @summary Health
 */
export type healthHealthGetResponse200 = {
  data: HealthHealthGet200
  status: 200
}
    
export type healthHealthGetResponseSuccess = (healthHealthGetResponse200) & {
  headers: Headers;
};
;

export type healthHealthGetResponse = (healthHealthGetResponseSuccess)

export const getHealthHealthGetUrl = () => {


  

  return `/health`
}

export const healthHealthGet = async ( options?: RequestInit): Promise<healthHealthGetResponse> => {
  
  const res = await fetch(getHealthHealthGetUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: healthHealthGetResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as healthHealthGetResponse
}
